---
name: My First Workflow
on:
  workflow_dispatch:
jobs: 
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multiple cmd
        run: |
          mkdir mydemo
          cd mydemo
          echo "Hello, world!" > hello.txt
          cat hello.txt
